# Generated by Django 4.1.3 on 2023-06-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerente',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gerente',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
