# Generated by Django 4.1.3 on 2023-06-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_gerente_apellido_alter_gerente_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desarrollador',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='desarrollador',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
